# Generated by Django 5.2.6 on 2025-10-01 05:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_paymentmethod_wallet_wallettransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income_goal', models.DecimalField(decimal_places=2, default=Decimal('3000.00'), help_text="User's target monthly income", max_digits=12)),
                ('monthly_expense_budget', models.DecimalField(decimal_places=2, default=Decimal('2500.00'), help_text="User's planned monthly expense budget", max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('income_goal_enabled', models.BooleanField(default=True)),
                ('budget_alerts_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_user_profile',
            },
        ),
    ]
