# Generated by Django 5.2.6 on 2025-09-24 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('ledgerID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matcher', models.CharField(max_length=255)),
                ('matcher_type', models.CharField(choices=[('regex', 'Regex'), ('keyword', 'Keyword')], max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('necessary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budgetID', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('period', models.CharField(max_length=200)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountID', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('A', 'Assets'), ('L', 'Liabilities'), ('I', 'Income'), ('E', 'Expenses')], max_length=1)),
                ('name', models.CharField(max_length=200)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='Splits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('desc', models.BooleanField()),
                ('necessary', models.BooleanField()),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.ledger')),
                ('splits', models.ManyToManyField(to='ledger.splits')),
                ('tags', models.ManyToManyField(blank=True, to='ledger.tag')),
            ],
        ),
    ]
