# Generated by Django 5.2.6 on 2025-09-24 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='type',
            new_name='account_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='ledger',
        ),
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='desc',
            field=models.TextField(),
        ),
    ]
