# Generated by Django 5.2.6 on 2025-09-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_rename_type_account_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ASSET', 'Assets'), ('LIABILITY', 'Liabilities'), ('INCOME', 'Income'), ('EXPENSE', 'Expenses')], max_length=20),
        ),
    ]
