# Generated by Django 5.2.6 on 2025-09-27 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_account_account_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transactionID',
            new_name='transactdaionID',
        ),
    ]
