# Generated by Django 5.2.6 on 2025-09-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_rename_transactionid_transaction_transactdaionid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('imported_count', models.IntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
