# Generated by Django 5.2.6 on 2025-09-28 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_importrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='splits',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transactdaionID',
            new_name='transactionID',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='necessary',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='ledger.transaction')),
            ],
        ),
        migrations.DeleteModel(
            name='Splits',
        ),
    ]
