# Generated by Django 5.2.6 on 2025-10-01 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_alter_tag_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alertID', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.budget')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
