# Generated by Django 5.2.6 on 2025-10-01 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.account'),
        ),
    ]
