# Generated by Django 5.2.7 on 2025-10-02 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_alter_importrecord_id_alter_rule_id_alter_split_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ledger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='ledger.ledger'),
        ),
    ]
