# Generated by Django 5.2.6 on 2025-10-02 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_account_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='ledger.ledger'),
        ),
    ]
